version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'jaso_search'
      MYSQL_ROOT_PASSWORD: 'team_password' # 팀원 공통 패스워드
    ports:
      - '3306:3306'
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci